// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");
var ReactSimpleMaps = require("react-simple-maps");

var class_tables = [
  0,
  0,
  0
];

function make(children) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return ReasonReact.wrapJsForReason(ReactSimpleMaps.Markers, Curry._1(class_tables[0], 0), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
